[C-2] Binary Tree Library
TupoSoft/c_dsa pull request #3
Opened 2023-01-28 02:04 UTC by irog-c

A binary tree library to conveniently deal with linked lists.

TODO:
- [ ] Write tests
- [ ] Add node deletion support

[**Trello task link**](https://trello.com/c/RR0de6LF/1-c-2-binary-tree-library)

2023-01-28 13:21 UTC, KyryloKupin requested changes

2023-01-28 13:21 UTC, KyryloKupin commented on binary_tree/src/binary_tree.c
> +    TreeNode *head = malloc(sizeof(TreeNode));
```suggestion
    TreeNode *head = malloc(sizeof *head);
```

2023-01-28 13:21 UTC, KyryloKupin commented on binary_tree/src/binary_tree.c
> +binary_tree_insert_element(TreeNode *head, const int val)
I think head should be a pointer to the pointer

2023-01-28 13:21 UTC, KyryloKupin commented on binary_tree/src/binary_tree.c
> +    if (head == NULL) return;
```suggestion
    if (!head) return;
```

2023-01-28 13:21 UTC, KyryloKupin commented on binary_tree/src/binary_tree.c
> +    if (head == NULL) return;
```suggestion
    if (!head) return;
```

2023-01-28 13:21 UTC, KyryloKupin commented on binary_tree/src/binary_tree.c
> +    }
Let's avoid nesting conditionals whenever possible

2023-01-28 16:31 UTC, irog-c commented on binary_tree/src/binary_tree.c
> +    }
Done

2023-01-28 16:31 UTC, irog-c commented on binary_tree/src/binary_tree.c
> +    if (head == NULL) return;
Done

2023-01-28 16:31 UTC, irog-c commented on binary_tree/src/binary_tree.c
> +binary_tree_insert_element(TreeNode *head, const int val)
It doesn't have to be if we return it

2023-01-28 16:31 UTC, irog-c commented on binary_tree/src/binary_tree.c
> +    TreeNode *head = malloc(sizeof(TreeNode));
Done

2023-01-28 16:31 UTC, irog-c commented on binary_tree/src/binary_tree.c
> +    if (head == NULL) return;
Done

2023-01-28 16:33 UTC, irog-c commented
@KyryloKupin one thing to note: if a test in one library subfolder is named the same as another library subfolder, the runner will fail.

2023-01-28 17:24 UTC, KyryloKupin commented
@igor-c thanks for the note! Do you want to try fixing it or you'd prefer me to do it?

2023-01-28 17:24 UTC, KyryloKupin requested changes

2023-01-28 17:24 UTC, KyryloKupin commented on binary_tree/src/binary_tree.c
> +}
Why is the return type TreeNode *? Void should be sufficient.

2023-01-28 17:24 UTC, KyryloKupin commented on binary_tree/src/binary_tree.c
> +        struct TreeNode *tmp = binary_tree_smallest_node(head->right);
TreeNode is a type. You can remove struct everywhere.
```suggestion
        TreeNode *tmp = binary_tree_smallest_node(head->right);
```

2023-01-28 17:24 UTC, KyryloKupin commented on binary_tree/src/binary_tree.c
> +    TreeNode *head = malloc(sizeof(*head));
Why do you parenthesize *head? We know that sizeof isn't a function :)

2023-01-28 23:18 UTC, irog-c commented on binary_tree/src/binary_tree.c
> +}
Done

2023-01-28 23:18 UTC, irog-c commented on binary_tree/src/binary_tree.c
> +        struct TreeNode *tmp = binary_tree_smallest_node(head->right);
Done

2023-01-28 23:19 UTC, irog-c commented on binary_tree/src/binary_tree.c
> +    TreeNode *head = malloc(sizeof(*head));
It's for readability, personally I like the style with the parentheses better

2023-01-28 23:20 UTC, irog-c commented
> @irog-c thanks for the note! Do you want to try fixing it or you'd prefer me to do it?

Perhaps we can make a task to completely re-work the testing?

2023-01-29 09:07 UTC, KyryloKupin commented
> > @irog-c thanks for the note! Do you want to try fixing it or you'd prefer me to do it?
> 
> Perhaps we can make a task to completely re-work the testing?

Sure, don't hesitate to create a task for me or yourself.

2023-01-29 09:13 UTC, KyryloKupin requested changes

2023-01-29 09:13 UTC, KyryloKupin commented on CMakeLists.txt
> +        target_link_libraries(${test_name} binary_tree)
```suggestion
target_link_libraries(${test_name} linked_list binary_tree)
```

2023-01-29 09:13 UTC, KyryloKupin commented on binary_tree/CMakeLists.txt
> +add_library(binary_tree src/binary_tree.c)
```suggestion
add_library(binary_tree src/binary_tree.c include/binary_tree.h)
```

2023-01-29 18:25 UTC, KyryloKupin commented on CMakeLists.txt
> +target_link_libraries(${test_name} linked_list binary_tree)
Please fix the indentation.

2023-01-30 22:05 UTC, irog-c commented on CMakeLists.txt
> +target_link_libraries(${test_name} linked_list binary_tree)
Done

2023-01-30 22:05 UTC, irog-c commented on binary_tree/tests/create_print_destroy_tree.c
> +    for (int i = 0; i < dataSize; ++i) head = binary_tree_insert_element(head, data[i]);
Done

2023-02-01 18:30 UTC, KyryloKupin commented on binary_tree/include/binary_tree.h
> +TreeNode *binary_tree_create_node(const int val);
Since we only create a binary tree from array, let's rename it to just `binary_tree_create`.

2023-02-02 00:57 UTC, irog-c commented on binary_tree/include/binary_tree.h
> +TreeNode *binary_tree_create_node(const int val);
But we create just a node here and return it, it might be misleading a bit, I believe certain binary tree operations rely on creating a new node in certain scenarios.

2023-02-02 02:59 UTC, KyryloKupin commented on binary_tree/include/binary_tree.h
> +TreeNode *binary_tree_create_node(const int val);
Oops, sorry, I had in mind the function `binary_tree_create_from_data`, not `binary_tree_create_node`

2023-02-06 02:23 UTC, irog-c commented on binary_tree/include/binary_tree.h
> +TreeNode *binary_tree_create_node(const int val);
Done.

2023-02-06 22:20 UTC, KyryloKupin approved these changes

2023-02-19 20:40 UTC, irog-c commented
@KyryloKupin We should use `NULL` in my opinion.

2023-02-19 20:41 UTC, merged